[package]
name = "dot-properties"
description = "Simple crate to read and write .properties files."
version = "0.2.0"
authors = ["Speykious <speykious@gmail.com>"]
repository = "https://github.com/Speykious/dot-properties"
license = "MIT"
edition = "2021"

[dependencies]
